[profile.default]
src = "src"
out = "out"
optimizer = true
optimizer_runs = 200

libs = ["lib"]
viaIR = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@chainlink/contracts/=lib/foundry-chainlink/"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
